blank_issues_enabled: false
contact_links:
  - name: Report a security vulnerability
    url: https://github.com/ken109/r2-lfs/security/advisories/new
    about: Please report security problems privately.
