/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/[_]admin/route'
import { Route as AdminIndexRouteImport } from './routes/[_]admin/index'
import { Route as AdminActivityRouteImport } from './routes/[_]admin/activity'
import { Route as AdminLocksRouteImport } from './routes/[_]admin/locks'
import { Route as AdminTokensRouteImport } from './routes/[_]admin/tokens'
import { Route as AdminReposOwnerNameRouteImport } from './routes/[_]admin/repos.$owner.$name'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  path: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLocksRoute = AdminLocksRouteImport.update({
  id: '/locks',
  path: '/locks',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTokensRoute = AdminTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReposOwnerNameRoute = AdminReposOwnerNameRouteImport.update({
  id: '/repos/$owner/$name',
  path: '/repos/$owner/$name',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_admin/activity': typeof AdminActivityRoute
  '/_admin/locks': typeof AdminLocksRoute
  '/_admin/tokens': typeof AdminTokensRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/repos/$owner/$name': typeof AdminReposOwnerNameRoute
}
export interface FileRoutesByTo {
  '/_admin/activity': typeof AdminActivityRoute
  '/_admin/locks': typeof AdminLocksRoute
  '/_admin/tokens': typeof AdminTokensRoute
  '/_admin': typeof AdminIndexRoute
  '/_admin/repos/$owner/$name': typeof AdminReposOwnerNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_admin/activity': typeof AdminActivityRoute
  '/_admin/locks': typeof AdminLocksRoute
  '/_admin/tokens': typeof AdminTokensRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/repos/$owner/$name': typeof AdminReposOwnerNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/_admin'
    | '/_admin/activity'
    | '/_admin/locks'
    | '/_admin/tokens'
    | '/_admin/'
    | '/_admin/repos/$owner/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/_admin/activity'
    | '/_admin/locks'
    | '/_admin/tokens'
    | '/_admin'
    | '/_admin/repos/$owner/$name'
  id:
    | '__root__'
    | '/_admin'
    | '/_admin/activity'
    | '/_admin/locks'
    | '/_admin/tokens'
    | '/_admin/'
    | '/_admin/repos/$owner/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: '/_admin'
      fullPath: '/_admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/_admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/activity': {
      id: '/_admin/activity'
      path: '/activity'
      fullPath: '/_admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/locks': {
      id: '/_admin/locks'
      path: '/locks'
      fullPath: '/_admin/locks'
      preLoaderRoute: typeof AdminLocksRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/tokens': {
      id: '/_admin/tokens'
      path: '/tokens'
      fullPath: '/_admin/tokens'
      preLoaderRoute: typeof AdminTokensRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/repos/$owner/$name': {
      id: '/_admin/repos/$owner/$name'
      path: '/repos/$owner/$name'
      fullPath: '/_admin/repos/$owner/$name'
      preLoaderRoute: typeof AdminReposOwnerNameRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminLocksRoute: typeof AdminLocksRoute
  AdminTokensRoute: typeof AdminTokensRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminReposOwnerNameRoute: typeof AdminReposOwnerNameRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminLocksRoute: AdminLocksRoute,
  AdminTokensRoute: AdminTokensRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminReposOwnerNameRoute: AdminReposOwnerNameRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
